### ISSUE TITLE
[2.1.2] Formulate questions to ask the client

### ISSUE THREAD

**Issue by pangyurui** [Alan2201038/INF2001-P5-7#10]
# Issue Details

## Description
This Sub-Issue is for me to create a list of questions to ask the client to gather more / missing requirements. I will also add in questions that helps to clarify some of the initial requirements.

## Goals
I will have created a list of questions that my team and I would be asking the Client.

## Success or Completion Criteria
A list of Interview Questions to ask the Client.

## Allocated Time
4 Days

**Start Date:** 01/09/23, 2200
**End Date:** 06/09/23, 2359

**Comment by alanwml** [comment]
# Issue Comments

## Description
- Created a list of 15 questions to ask the Client. I have created 15 questions so that my team and I can pace each question to a minute so that we do not let our Client go astray during the Interview.

## Changes to success or completion criteria?: y/n (if y, describe)
No changes, Criteria Completed!

**Start Date:** 31/08/23, 1800
**End Date:** 31/08/23, 2359

## Related Issue
Detailed Interview Questions is in the Team Minutes:
- #9
