### ISSUE TITLE
[1.3.2.2] Validate Functional Requirements

### ISSUE THREAD

**Issue by alanwml** [Alan2201038/INF2001-P5-7#34]
# Issue Details

## Description
Validate Functional Requirements (FRs), to make sure our FRs, that we created on a previous issue, are good based on the 7 aspects.

## Goals.
To decide on a final set of functional requirements so that we can start working on estimation and planning.

## Success or Completion Criteria
A list of Validated Functional Requirements to be used in our Software Requirements Specification (SRS) Report and to be used for estimation and planning.

## Allocated Time
4 days

**Start Date:** 08/09/23, 0900
**End Date:** 13/09/23, 2359

**Comment by git-clone-xen** [comment]
Refined and updated current Functional Requirements on 13/09/2023:


FR1: The system shall provide a web-based Dashboard interface for Managers to access and view a weekly workload summary on the Dashboard Page.
FR2: The system shall show staff names exceeding 40 working hours, their current weekly hours, and monthly weekend and carriage counts on the Dashboard Page. 
FR3: The system shall display the top three staff names with the lowest working hours and their currently accumulated working hours for the current week, at the Manager’s Dashboard Page.
FR4: The system shall allow Managers to sort the weekly summary by different staff roles for effective planning. [ Additional ]
FR5: The system shall provide a Job Assignment Page for Managers to view and assign shifts, with the options to display shifts in either a monthly or weekly view.
FR6: The system shall allow Managers to access and review the details of all assigned Staff Members for the shifts, such as their job role, availability, preference and current location, on the Job Assignment Page.
FR7: The system shall allow Managers to access and review the availability of up to three Staff Members for the shifts, with the current workload and location, on the Job Assignment Page.
FR8: The system shall allow Managers to assign individual Staff Members to shifts based on their job preferences on the Job Assignment Page.
FR9: The system shall generate a pop-up window on the Job Assignment Page to confirm the allocation of an Individual Staff Member into a designated shift after the Manager has made the assignment.
FR10: The system shall allow the Manager to confirm the allocation of the assigned Staff Member into the designated shift, on the pop-up window.
FR11: The system shall allow the Manager to cancel the allocation of the assigned Staff Member into the designated shift on the pop-up window, allowing the Manager to reassign the Staff Member to another shift.
FR12: The system shall update job allocations, with a response time not exceeding 3 seconds, to facilitate Managers in assigning jobs for staff members who might be affected by previous shift allocations, on the Job Assignment Page.

**Comment by alanwml** [comment]
Refined and updated more current Functional Requirements on 13/09/2023:
FR13: The system shall allow Managers to finalize the schedule by submitting the assigned jobs for the upcoming week, starting from the current week’s Thursday 0000 hours, up to the current week’s Sunday 2359 hours, on the Job Assignment Page. 
FR14: The system shall generate a pop-up window when the Manager exits the Job Assignment Page, provided that the schedule for the upcoming week does not meet the minimum staff requirements of two engine drivers, one conductor, one assistant conductor, and one cleaner for every two carriages per train.
FR15: The system shall allow the Manager the option to either proceed with the current allocation plan and exit the Job Assignment Page.
FR16: The system shall allow the Manager to close the pop-up window to continue allocation.
FR17: The system shall provide a Notification Page for the Managers to receive notifications and reminders regarding the shift schedules and staff concerns?? 
FR18: The system shall generate a notification displayed on the Notification Page for the Manager if the schedule for the upcoming week does not meet the minimum staff requirements of two engine drivers, one conductor, one assistant conductor, and one cleaner for every two carriages per train.
FR19: The system shall generate another notification displayed on the Notification Page for the Manager if the schedule for the upcoming week still does not meet the minimum staff requirements of two engine drivers, one conductor, one assistant conductor, and one cleaner for every two carriages per train by the current week’s Sunday 0700.
FR20: The system shall generate a notification displayed on the Notification Page for the Manager if the schedule for the upcoming week has not been assigned at all by the current week’s Sunday 0700.
FR21: The system shall allow the Manager to review the notification on the Notification Page and continue allocating the schedule for the week that has been notified, before the current week’s Sunday 2359.
FR22: The system shall allow Managers to modify all assigned shift schedules for the upcoming week before the current week’s Sunday 2359.
FR23: The system shall provide a Staff Page that allows Managers to access and view all Staff Members, along with their contact numbers, job roles, and hours worked for the current week, on a single scrollable page.
FR24: The system shall allow Managers to enter the name of a Staff Member to access their availability, job preferences, workload, and current location on the Staff Page.

**Comment by git-clone-xen** [comment]
Refined and updated more current Functional Requirements on 13/09/2023:

FR25: The system shall allow Managers to sort the displayed table by offering sorting options including no sorting, least amount of hours worked per week, and most amount of hours worked per week on the Staff Page.
FR26: The system shall allow Managers to review all rejection requests for jobs allocated to Staff Members, including the Staff Member's name, shift details, and the reason for rejection, on the Notification Page.
FR27: The system shall allow Managers to decline the request for rejecting assigned jobs for the Staff member on the Notification Page.
FR28: The system shall allow Managers to approve the request for rejecting assigned jobs for the Staff member on the Notification Page.
FR29: The system shall allow Managers to approve or decline staff availability requests from Staff Members that have missed the weekly deadline for the upcoming week, on a case-by-case basis from the current week’s Thursday 0000 hours to Sunday 2359 hours, on the Notification Page.
FR30: The system shall require Managers to reassign the affected staff member's duties upon approving their staff availability request, to another available staff member before finalizing the schedule on the Job Assignment Page.
FR31: The system shall allow Managers to contact staff members through the system.
Instead of Email & Texting, use the UI as a one stop.
FR32: The system shall allow Managers to contact IT admins through the system.
FR33: The system shall provide a web-based Dashboard Page for Staff Members to access and review their job schedules, with the option to view the schedule on either a weekly or monthly basis.
FR34: The system shall allow Staff Members to navigate between previous and upcoming weeks or months of their job schedules, on the Dashboard Page.
FR35: The system shall allow Staff Members to specify and modify their work availability and their shift preferences for dates up to five weeks  in advance, on the Dashboard Page.
FR36: The system shall allow Staff Members to modify their availability for the upcoming week, any time before the current week’s Wednesday 2359 hours, on the Dashboard Page. 
FR37: The system shall not allow Staff Members to modify their work availability and shift preferences for the upcoming week on the Dashboard Page, once the current week’s Thursday 0000 hours has passed.

**Comment by alanwml** [comment]
Refined and update more current Functional Requirements on 13/09/23:

FR38: The system shall provide a Notification Page for Staff Members to receive notifications, reminders, updates, and requests submitted regarding their shift schedules.
FR39: The system should notify staff members of jobs that have been allocated to them on the Notification Page.
FR40: The system shall provide Staff Members to view the details of jobs that have been allocated to them, on the Dashboard Page.
FR41: The system shall allow Staff Members to submit a rejection request for a job allocated to them, with a minimum notice of x days before the scheduled shift, on the Dashboard Page.
FR42: The system shall generate a notification on the Notification Page for the Staff Member upon submitting the rejection request for a job allocated to them.
FR43: The system shall allow Staff Members to cancel their rejection request for a job allocated to them, before the request was processed, on the Notification Page.
FR44: The system shall allow staff members to contact Managers through the system.
FR45: The system shall allow staff members to contact IT admins through the system.
FR46: The system shall allow IT admins to manage accounts, including creating, deleting, searching, modifying, and viewing all accounts within the system.
FR47: The system shall allow IT admins to contact any staff through the system.
FR48: The system shall allow all Staff Members, Managers and IT admins to enter the Dashboard Page when provided with the correct username and password on the Login Page.
FR49: The system shall allow all Staff Members, Managers and IT admins to change and reset their password, at the Account Settings Page only when provided with the correct current password  for verification.
FR50: The system shall allow all Staff Members, Managers and IT admins to reset their password, at the Login Page only when provided with the correct current password for verification.
FR51: The system shall allow all staff members and Managers to change their display photo.

**Comment by alanwml** [comment]
# Issue Comments

## Description
Validated and finalized 51 FRs with Xen.

## Changes to success or completion criteria? y/n (if y, describe)
No Changes, Issue Completed!

Start Date: 08/09/23, 0900
End Date: 13/09/23, 2359
