### ISSUE TITLE
Team Meeting Minutes #1

### ISSUE THREAD

**Issue by Alan2201038** [Alan2201038/INF2001-P5-7#9]
Start Date: 06/09/2023
End Date: 06/09/2023

Minutes & To-do tasks from this meeting.

**Comment by xoXen** [comment]
6/9/2023 9PM - 9:50PM

Discussed and finalized questions to clarify with client, for meeting on 7/9/2023. 

1. Just to confirm, who are the Actors for the System and What can they do? [ To be added if there’s any more Actors ]
   a. IT Department
   b. Managers
   c.  Workers

2. What happens if Worker assigned work but ends up MIA or Sick?

3. Can we assume that there is no maintenance/breakdown?

5. “One assistant conductor and a cleaner will also be assigned for every two passenger carriages.” - What happens if there is an odd number of carriages? 
 
6. All 5 Trains being Used? How is that possible? Are all 5 trains being used or just 4

7. Will a train be on service?

8. What are the shifts like?
   a. 8hr, 8hr, 4hr?
   b. 4hr * 5

9. What are the minimum and maximum number of hours a staff can work per week

10. What specific information should be displayed on the manager's landing page to visualize staff workload immediately?

11. What information should be collected when staff indicate their availability up to one week earlier?

12. What specific details should be displayed when visualizing staff availability, workload, job preferences, and location on the job allocation page?

13. Are there any validation rules for availability entries by the staff?

14. What is the process for staff to reject jobs, and what notifications or warnings should be provided when they do so?

15. Are there reporting or analytics requirements for tracking employee workload, job allocation efficiency, or other key performance indicators?

16. How long should the data history be retained in the system?

17. What are the expected user loads?

18. How to login? Staff pass to login?

19. Industry requirements. PDPA?

**Comment by motorfireman** [comment]
1. Just to confirm, who are the Actors for the System and What can they do? [To be added if there’s any more Actors]
a. IT Department
b. Managers
c. Workers
2. What happens if Worker assigned work but ends up MIA or Sick? Shouldn’t there be always a backup shift. Example, standby team but they are at home.
3. Can we assume that there is no maintenance/breakdown/servicing? Yes or No
4. “One assistant conductor and a cleaner will also be assigned for every two passenger carriages.” - What happens if there is an odd number of carriages? 
5. If the train at SG, should it end at SG? 
6.What are the shifts like?
A. 8hr, 8hr, 4hr?                     B. 4hr * 5?                             C. 12hr and 8hr?
7. What are the minimum and maximum number of hours a staff can work per week? _____
8. How long should the data history be retained in the system? Also the data history how far back you want to retain?
9. What are the expected user loads? (non functional requirement)
10. Is there any Industry requirements we must adhere to. WCAG, PDPA? 
11. If employees miss weekly deadline submission How do you want us to deal with it? Send an email to the affected employees and respective manager?
12. How does the manager want to handle the case-by-case basis via the Web App?	
13. For the first trains do they start at both ends? Yes or no
14. Are there any additional functions or features that you envision for this workload management system but we didn’t mention? DO you have anything else I say that we didn’t mention 
15. GPS and Feedback system

**Comment by motorfireman** [comment]
These questions need further clarification and can be sent as email.

1.	All 5 Trains being used? How is that possible? Are all 5 trains being used, or just 4 (not important)
2.	What specific information should be displayed on the manager's landing page to visualize staff workload immediately? You mention essential information, what are they?
3.	What information should be collected when staff indicate their availability up to one week earlier?
4.	What specific details should be displayed when visualizing staff availability, workload, job preferences, and location on the job allocation page?
5.	Are there any validation rules for availability entries by the staff? (you need to give examples of validation rules must have some kind of authentication before performing any actions)
6.	What is the process for staff to reject jobs, and what notifications or warnings should be provided when they do so?
7.	Are there reporting or analytics requirements for tracking employee workload, job allocation efficiency, or other key performance indicators?
8.	How to login? Staff pass to log in?
“Trains should not stay stationary for more than three hours”

Specific Carriage numbers on each train (7-13) 
1.	train 1:
1.	train 2:

Scalability and Future Expansion:
Do you anticipate any growth or changes in the train operation division that the system should accommodate in the future?

Are there plans to expand the number of trains, routes, or employees in the future?

**Comment by git-clone-xen** [comment]
# Issue Comments

## Description
- Team discussion and meeting. 
- Focused on the requirements. (Initial, Functional & Non-functional)
- Crafted questions to clarify with client. 


## Changes to success or completion criteria? 
No changes, Criteria Completed.

Start Date: 06/09/2023
End Date: 06/09/2023
